### ISSUE TITLE
An error occurs when creating a folder with the same name as an existed file.

### ISSUE THREAD

**Issue by WoodwindHu** [elliot40404/bonk#11]
As shown in the following figure:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/28439907/211187095-cb2e0116-adab-4232-bc33-ea7cb0d3b80a.png">
Platform: MacOs

**Comment by elliot40404** [comment]
This is not actually a problem this is just a limitation of how OS's handle files and directories, you cannot have a file and a directory with the same name in the same directory. Though what can be improved is throwing the correct error message.
