### ISSUE TITLE
bonk will fail to touch existing files

### ISSUE THREAD

**Issue by BartMassey** [elliot40404/bonk#4]
If you `bonk` a file that has existing content, that content will be truncated by `std::fs::File::create()`.

**Comment by BartMassey** [comment]
No it won't. My bad. Instead it will refuse to touch the file, crashing with an error.

**Comment by elliot40404** [comment]
Currently bonk only creates file if they do not exist

**Comment by BartMassey** [comment]
That's fine, but in this case please don't describe it as a "touch alternative" in the `README`. That description carries with it the expectation that `bonk` will have the core function of `touch`, namely updating the write time of a file.
