### ISSUE TITLE
URGENT: bonk will delete file contents

### ISSUE THREAD

**Issue by BartMassey** [elliot40404/bonk#7]
Running `bonk` on an existing file will delete its contents.

```sh
$ echo hello >/tmp/hello.txt
$ cat /tmp/hello.txt
hello
$ cargo run /tmp/hello.txt
$ cat /tmp/hello.txt
$
```

Please see <http://github.com/BartMassey/touche> for a touch-like inspired by `bonk` that avoids this sort of problem.

**Comment by elliot40404** [comment]
Resolved in 0.3.0. Also thanks for actively reporting the issues.
