### ISSUE TITLE
getting issues of these 

### ISSUE THREAD

**Issue by kasinadhsarma2** [elliot40404/bonk#8]
![image](https://user-images.githubusercontent.com/81065703/192560870-f17d3b96-cb1a-4713-91d4-fa72f0e13956.png)

some compilation errors are there update these

**Comment by elliot40404** [comment]
Hello [kasinadhsarma](https://github.com/kasinadhsarma),
You need to upgrade your rust version from `1.59.0` to `1.63.0` or newer, this can be done with the `rustup update` command . Or you install the prebuilt binary from the releases page. Also make sure you download the latest v0.3.0 binary.
I will fix this in the next version.
Thanks
