### ISSUE TITLE
SCoop-pacakge ! request

### ISSUE THREAD

**Issue by OmiChrome** [elliot40404/bonk#9]
i liked how bonk is so useful . and make work so eaasy

it would be good if u add scoop-manifest for window user 
[scoop.sh](https://scoop.sh/) is a package -manager for window 🥺 

please make it avaible there

**Comment by elliot40404** [comment]
Sure will look into this.

**Comment by OmiChrome** [comment]
> Sure will look into this.

OMG , Thx :D

**Comment by deadcoder0904** [comment]
Yes, would love this.

Currently, I get errors doing a `cargo install` so would like either `scoop` or `winget` installation.

I tried using Powershell on Windows like:

```bash
# ni works to create new files
# ni input.tsx or New-Item input.tsx
Set-Alias touch ni
# now i can do
# touch input.tsx
```

But this doesn't support multiple files even on Powershell 7 so need to use this somehow.

**Comment by elliot40404** [comment]
@deadcoder0904 Scoop package now available
```sh
scoop install https://raw.githubusercontent.com/elliot40404/bonk/master/bonk.json
```

**Comment by deadcoder0904** [comment]
hot damn, that was fast.
